export const Roles = {
  VISITOR: "VISITOR",
  BRAND: "BRAND",
  CREATOR: "CREATOR",
  ADMIN: "ADMIN",
  DEV: "DEV",
};

export const Pv = {
  INITIAL: "INITIAL",
  APPROVED: "APPROVED",
  PENDING: "PENDING",
  REJECTED: "REJECTED",
  COMPLETED: "COMPLETED",
};

export const Experience = {
  BEGINNER: "BEGINNER",
  INTERMEDIATE: "INTERMEDIATE",
  EXPERT: "EXPERT",
};
